services:
  postgres:
    image: postgres:17 

    container_name: industrial-ai-postgres

    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: industrial_ai 

    ports:
      - "5433:5432" 

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: