"""create metric definitions table

Revision ID: bcda7e825c3a
Revises: 3b418b5951f8
Create Date: 2026-06-02 17:02:45.304252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcda7e825c3a"
down_revision: Union[str, Sequence[str], None] = "3b418b5951f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("asset_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_definitions")
    # ### end Alembic commands ###
